# 应用名称
spring:
  application:
    name: activity-interface
  profiles:
    active: dev
server:
  servlet:
    context-path: /activity
  port: 9199

# log
logging:
  file:
    path: /home/app/logs/activity

# arthas
arthas:
  agent-id: 6qXobHvLhFyRcNZk
  tunnel-server: ws://139.155.183.87:7777/ws

# actuator
management:
  endpoints:
    web:
      exposure:
        include: [ "*" ]